#%RAML 1.0
version: v1
title: PunchOut Catalog API
baseUri: https://localhost:8081/api
protocols: [ HTTPS ]
/oci:
  /PunchOutSetup:
    get:
      queryParameters:
        USERNAME:
          description: Username
          type:        string
          example:     "lbailey@mrc.com"
        PASSWORD:
          description: Password
          type:        string
          example:     "password"
        HOOKURL:
          description: URL where to return the contents of the cart.
          type:        string
          example:     "http://mock-buyer.us-e1.cloudhub.io/oci"
        BUYER_USERNAME:
          description: Buyer Username
          type:        string
          example:     "lbailey"
        FUNCTION:
          enum:       [VALIDATE, SEARCH, BACKGROUND_SEARCH]
          required:   false
        SEARCHSTRING:
          description: Search string
          type:       string
          required:   false
        PRODUCTID:
          description: Product ID
          type:       string
          required:   false
  /callback:
    post:
      body:
        application/json:
          example:
            !include cart.json
      responses:
        200:
          body:
            application/json:
              example:
                {
                    "Status": "Success",
                    "Type": "OCI"
                }            
/cif:
  get:
    displayName: CIF Catalog
    description: Generates updated CIF Catalog for Level 2 Punchout
    responses:
      200:        
/cxml:  
  get:
    displayName: cXML Tester
    description: Provides an interface to test a cXML message
    responses:
      200:         
  post:    
    displayName: cXML PunchOut Setup
    body:
      application/x-www-form-urlencoded:        
    responses:
      200:
        body:
          application/xml:
            example:
              <cXML timestamp="2019-02-07T10:37:16.882-06:00" lang="en-US">
              <Response>
                <Status code="200" text="OK"/>
                <PunchOutSetupResponse>
                  <StartPage>
                    <URL>
                    https://sdodemo-main-166ce2cf6b6-1683e62625a.force.com/DefaultStore/login?pw=Y2Flc2Fyczc3Nw%3D%3D&un=cGFydHN4cHJlc3NAY2Flc2Fycy5jb20%3D
                    </URL>
                  </StartPage>
                </PunchOutSetupResponse>
              </Response>
              </cXML>
  /authenticate:
    get:
      queryParameters:
        ukey:
          description: Base64 encoded username
          type:        string
          example:     "cGFydHN4cHJlc3NAY2Flc2Fycy5jb20%3D"
        pkey:
          description: Base64 encoded password
          type:        string
          example:     "Y2Flc2Fyczc3Nw%3D%3D"
  /callback:
    post:
      body:
        application/json:
          example:
            !include cart.json
      responses:
        200:
          body:
            application/json:
              example:
                { 
                  "Status":"Success"
                }